[package]
name = "rustory"
version = "0.1.0"
authors = ["agumonkey"]

[dependencies]
reqwest = "0.9.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.rusqlite]
version = "0.23.0"
features = ["bundled"]